<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function easyopac_reset_password_menu() {
  $items = [];
  $items['admin/config/people/password'] = [
    'title' => 'Password reset',
    'description' => 'Enable/Disable password reset feature.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['easyopac_reset_password_settings_form'],
    'access arguments' => ['access administration pages'],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function easyopac_reset_password_menu_alter(&$items) {
  if (!empty(variable_get('easyopac_reset_password_feature', FALSE))) {
    $items['user/password']['access callback'] = TRUE;
  }
}

/**
 * Reset password feature configuration form.
 */
function easyopac_reset_password_settings_form(&$form, &$form_state) {
  $form['easyopac_reset_password_feature'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable password reset'),
    '#description' => t('Enable or disable password reset feature.'),
    '#default_value' => variable_get('easyopac_reset_password_feature', FALSE),
  ];

  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t('Save configuration'),
  ];

  return $form;
}

/**
 * Reset password feature configuration form submit handler.
 */
function easyopac_reset_password_settings_form_submit($form, &$form_state) {
  variable_set('easyopac_reset_password_feature', $form_state['values']['easyopac_reset_password_feature']);
  drupal_set_message(t('The password reset settings have been updated and menu cache has been rebuilt.'));
  menu_rebuild();
}
